package telemetry

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS request_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		ts_unix INTEGER NOT NULL,
		request_id TEXT NOT NULL,
		site_id TEXT NOT NULL DEFAULT '',
		site_name TEXT NOT NULL DEFAULT '',
		rule_id TEXT NOT NULL DEFAULT '',
		is_internal INTEGER NOT NULL DEFAULT 0,
		method TEXT NOT NULL,
		scheme TEXT NOT NULL,
		host TEXT NOT NULL,
		path TEXT NOT NULL,
		raw_query TEXT NOT NULL DEFAULT '',
		remote_ip TEXT NOT NULL DEFAULT '',
		user_agent TEXT NOT NULL DEFAULT '',
		referer TEXT NOT NULL DEFAULT '',
		cache_state TEXT NOT NULL DEFAULT '',
		cache_status TEXT NOT NULL DEFAULT '',
		status_code INTEGER NOT NULL DEFAULT 0,
		response_bytes INTEGER NOT NULL DEFAULT 0,
		total_duration_ms INTEGER NOT NULL DEFAULT 0,
		origin_requests INTEGER NOT NULL DEFAULT 0,
		origin_status_code INTEGER NOT NULL DEFAULT 0,
		origin_duration_ms INTEGER NOT NULL DEFAULT 0,
		error_kind TEXT NOT NULL DEFAULT '',
		upstream_host TEXT NOT NULL DEFAULT '',
		content_type TEXT NOT NULL DEFAULT ''
	)`,
	`CREATE INDEX IF NOT EXISTS idx_request_logs_ts ON request_logs(ts_unix DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_request_logs_site_ts ON request_logs(site_id, ts_unix DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_request_logs_path_ts ON request_logs(path, ts_unix DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_request_logs_request_id ON request_logs(request_id)`,
	`CREATE TABLE IF NOT EXISTS audit_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		ts_unix INTEGER NOT NULL,
		request_id TEXT NOT NULL DEFAULT '',
		remote_ip TEXT NOT NULL DEFAULT '',
		method TEXT NOT NULL DEFAULT '',
		path TEXT NOT NULL DEFAULT '',
		action TEXT NOT NULL,
		resource_type TEXT NOT NULL,
		resource_id TEXT NOT NULL,
		summary TEXT NOT NULL DEFAULT '',
		status_code INTEGER NOT NULL DEFAULT 0
	)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_logs_ts ON audit_logs(ts_unix DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_type, resource_id, ts_unix DESC, id DESC)`,
	`CREATE TABLE IF NOT EXISTS metric_rollups_minute (
		bucket_unix INTEGER NOT NULL,
		site_id TEXT NOT NULL,
		requests INTEGER NOT NULL DEFAULT 0,
		hit_requests INTEGER NOT NULL DEFAULT 0,
		stale_requests INTEGER NOT NULL DEFAULT 0,
		miss_requests INTEGER NOT NULL DEFAULT 0,
		bypass_requests INTEGER NOT NULL DEFAULT 0,
		error_requests INTEGER NOT NULL DEFAULT 0,
		edge_bytes INTEGER NOT NULL DEFAULT 0,
		cached_bytes INTEGER NOT NULL DEFAULT 0,
		origin_requests INTEGER NOT NULL DEFAULT 0,
		origin_bytes INTEGER NOT NULL DEFAULT 0,
		status_2xx INTEGER NOT NULL DEFAULT 0,
		status_3xx INTEGER NOT NULL DEFAULT 0,
		status_4xx INTEGER NOT NULL DEFAULT 0,
		status_5xx INTEGER NOT NULL DEFAULT 0,
		total_duration_ms INTEGER NOT NULL DEFAULT 0,
		total_duration_count INTEGER NOT NULL DEFAULT 0,
		origin_duration_ms INTEGER NOT NULL DEFAULT 0,
		origin_duration_count INTEGER NOT NULL DEFAULT 0,
		edge_le_10 INTEGER NOT NULL DEFAULT 0,
		edge_le_25 INTEGER NOT NULL DEFAULT 0,
		edge_le_50 INTEGER NOT NULL DEFAULT 0,
		edge_le_100 INTEGER NOT NULL DEFAULT 0,
		edge_le_250 INTEGER NOT NULL DEFAULT 0,
		edge_le_500 INTEGER NOT NULL DEFAULT 0,
		edge_le_1000 INTEGER NOT NULL DEFAULT 0,
		edge_le_2500 INTEGER NOT NULL DEFAULT 0,
		edge_gt_2500 INTEGER NOT NULL DEFAULT 0,
		origin_le_10 INTEGER NOT NULL DEFAULT 0,
		origin_le_25 INTEGER NOT NULL DEFAULT 0,
		origin_le_50 INTEGER NOT NULL DEFAULT 0,
		origin_le_100 INTEGER NOT NULL DEFAULT 0,
		origin_le_250 INTEGER NOT NULL DEFAULT 0,
		origin_le_500 INTEGER NOT NULL DEFAULT 0,
		origin_le_1000 INTEGER NOT NULL DEFAULT 0,
		origin_le_2500 INTEGER NOT NULL DEFAULT 0,
		origin_gt_2500 INTEGER NOT NULL DEFAULT 0,
		method_get INTEGER NOT NULL DEFAULT 0,
		method_head INTEGER NOT NULL DEFAULT 0,
		method_post INTEGER NOT NULL DEFAULT 0,
		method_put INTEGER NOT NULL DEFAULT 0,
		method_delete INTEGER NOT NULL DEFAULT 0,
		method_patch INTEGER NOT NULL DEFAULT 0,
		method_options INTEGER NOT NULL DEFAULT 0,
		method_other INTEGER NOT NULL DEFAULT 0,
		PRIMARY KEY (bucket_unix, site_id)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_metric_rollups_site_bucket ON metric_rollups_minute(site_id, bucket_unix DESC)`,
}

func buildRollupUpsertSQL() string {
	return `
		INSERT INTO metric_rollups_minute (
			bucket_unix, site_id, requests, hit_requests, stale_requests, miss_requests, bypass_requests, error_requests,
			edge_bytes, cached_bytes, origin_requests, origin_bytes,
			status_2xx, status_3xx, status_4xx, status_5xx,
			total_duration_ms, total_duration_count, origin_duration_ms, origin_duration_count,
			edge_le_10, edge_le_25, edge_le_50, edge_le_100, edge_le_250, edge_le_500, edge_le_1000, edge_le_2500, edge_gt_2500,
			origin_le_10, origin_le_25, origin_le_50, origin_le_100, origin_le_250, origin_le_500, origin_le_1000, origin_le_2500, origin_gt_2500,
			method_get, method_head, method_post, method_put, method_delete, method_patch, method_options, method_other
		) VALUES (
			?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
			?, ?, ?, ?, ?, ?, ?, ?, ?,
			?, ?, ?, ?, ?, ?, ?, ?, ?,
			?, ?, ?, ?, ?, ?, ?, ?
		)
		ON CONFLICT(bucket_unix, site_id) DO UPDATE SET
			requests = requests + excluded.requests,
			hit_requests = hit_requests + excluded.hit_requests,
			stale_requests = stale_requests + excluded.stale_requests,
			miss_requests = miss_requests + excluded.miss_requests,
			bypass_requests = bypass_requests + excluded.bypass_requests,
			error_requests = error_requests + excluded.error_requests,
			edge_bytes = edge_bytes + excluded.edge_bytes,
			cached_bytes = cached_bytes + excluded.cached_bytes,
			origin_requests = origin_requests + excluded.origin_requests,
			origin_bytes = origin_bytes + excluded.origin_bytes,
			status_2xx = status_2xx + excluded.status_2xx,
			status_3xx = status_3xx + excluded.status_3xx,
			status_4xx = status_4xx + excluded.status_4xx,
			status_5xx = status_5xx + excluded.status_5xx,
			total_duration_ms = total_duration_ms + excluded.total_duration_ms,
			total_duration_count = total_duration_count + excluded.total_duration_count,
			origin_duration_ms = origin_duration_ms + excluded.origin_duration_ms,
			origin_duration_count = origin_duration_count + excluded.origin_duration_count,
			edge_le_10 = edge_le_10 + excluded.edge_le_10,
			edge_le_25 = edge_le_25 + excluded.edge_le_25,
			edge_le_50 = edge_le_50 + excluded.edge_le_50,
			edge_le_100 = edge_le_100 + excluded.edge_le_100,
			edge_le_250 = edge_le_250 + excluded.edge_le_250,
			edge_le_500 = edge_le_500 + excluded.edge_le_500,
			edge_le_1000 = edge_le_1000 + excluded.edge_le_1000,
			edge_le_2500 = edge_le_2500 + excluded.edge_le_2500,
			edge_gt_2500 = edge_gt_2500 + excluded.edge_gt_2500,
			origin_le_10 = origin_le_10 + excluded.origin_le_10,
			origin_le_25 = origin_le_25 + excluded.origin_le_25,
			origin_le_50 = origin_le_50 + excluded.origin_le_50,
			origin_le_100 = origin_le_100 + excluded.origin_le_100,
			origin_le_250 = origin_le_250 + excluded.origin_le_250,
			origin_le_500 = origin_le_500 + excluded.origin_le_500,
			origin_le_1000 = origin_le_1000 + excluded.origin_le_1000,
			origin_le_2500 = origin_le_2500 + excluded.origin_le_2500,
			origin_gt_2500 = origin_gt_2500 + excluded.origin_gt_2500,
			method_get = method_get + excluded.method_get,
			method_head = method_head + excluded.method_head,
			method_post = method_post + excluded.method_post,
			method_put = method_put + excluded.method_put,
			method_delete = method_delete + excluded.method_delete,
			method_patch = method_patch + excluded.method_patch,
			method_options = method_options + excluded.method_options,
			method_other = method_other + excluded.method_other
	`
}
